# Generated by Django 2.0.2 on 2018-03-01 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128)),
                ('number_house', models.IntegerField(null=True)),
                ('number_flat', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_email', models.IntegerField(choices=[(0, 'prywatny'), (1, 'służbowy')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('group', models.ManyToManyField(to='phone_book_app.Groups')),
                ('person_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_adress', to='phone_book_app.Address')),
                ('person_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_book_app.Email')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_phone', models.IntegerField(choices=[(0, 'domowy'), (1, 'służbowy'), (2, 'komórkowy')], default=2)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='person_phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_book_app.Phone'),
        ),
    ]
