# Generated by Django 2.0.2 on 2018-03-01 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phone_book_app.Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phone_book_app.Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phone_book_app.Phone'),
        ),
    ]
