# Generated by Django 2.0.2 on 2018-03-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book_app', '0003_auto_20180301_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='adress_email',
            new_name='address_email',
        ),
    ]
