# Generated by Django 2.0.2 on 2018-03-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book_app', '0004_auto_20180301_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='address_email',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
