# Generated by Django 2.0.2 on 2018-04-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book_app', '0007_auto_20180302_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='group',
        ),
    ]
